version: '2.1'
services:
  redis:
    image: redis:alpine

  event-store:
    image: eventstore/eventstore

  models-api:
    image: 12grapes/models-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile-models-api
    links:
      - event-store
      - redis

  commands-api:
    image: 12grapes/commands-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile-commands-api
    links:
      - event-store
      - redis

  eventhandlers:
    image: 12grapes/eventhandlers
    build:
      context: .
      dockerfile: ./docker/Dockerfile-eventhandlers
    links:
      - event-store
      - redis

  app-test:
    image: 12grapes/app-test
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app-test
    links:
      - commands-api
      - models-api
      - event-store
      - redis
