version: '2.1'
services:
  redis:
    expose:
      - "6379"
    ports:
      - "6379:6379"

  event-store:
    expose:
      - "1113"
      - "2113"
    ports:
      - "1113:1113"
      - "2113:2113"

  models-api:
    environment:
      - PORT=8080
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/api/healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3

  commands-api:
    environment:
      - PORT=8081
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081/api/healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3

  counter-eventhandler:
    volumes:
      - .:/usr/app
    depends_on:
      commands-api:
        condition: service_healthy
      models-api:
        condition: service_healthy
