version: '2.1'
services:
  redis:
    expose:
      - "6379"
    ports:
      - "6379:6379"

  event-store:
    expose:
      - "1113"
      - "2113"
    ports:
      - "1113:1113"
      - "2113:2113"

  models-api:
    environment:
      - PORT=8080
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app

  commands-api:
    environment:
      - PORT=8081
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/app

  counter-eventhandler:
    volumes:
      - .:/usr/app
